### PR TITLE
Simplify adding `McJavaChecks` dependency

### LINKED ISSUE #659: Re-enable `McJavaChecksDependencyTest.addToProject()`
The test was disabled because resolution of dependencies strangely fails deep inside Gradle (after it was [bumped](#654) to v7.1.1).

It needs to be investigated why 3rd party dependencies (like Error Prone, or Protobuf) cannot be resolved even assuming that stub project under the test declares `mavenCentral()` and `mavenLocal()` as the repositories, _and_ the dependencies that were reported as missing, _are_ available at Maven Central.

It would be good to have a more lightweight mechanism of checking if a Spine Java Checks artifact is available. The current way of doing this is `Configuration.getResolvedConfiguration()`, which downloads the dependencies, is too slow.

### PR DESCRIPTION
**Pull request by alexander-yevsyukov**
This PR:
  * Changes the way of checking a Gradle dependency from using `Configuration.getResolvedConfiguration()` (which downloads artifacts) to `Configuration.getIncoming().getResolutionResult()` (which does not download). 
  * The previous item automatically fixes #659, which was caused by locking issues deep inside Gradle, when running under our tests.

The Gradle version was also bumped to 7.2.

### CODE REVIEW

File: buildSrc/src/main/kotlin/io/spine/internal/gradle/ConfigTester.kt [hunk 1]
```diff
@@ -0,0 +1,354 @@
...
+    /**
+     * The name of this repository.
+     */
+    val name: String
+
+    init {
+        name = repoName(uri)
+    }
+
+    fun prepareCheckout(destinationFolder: File): File {
```
Comment (yuri-sergiichuk) [inline buildSrc/src/main/kotlin/io/spine/internal/gradle/ConfigTester.kt:174]: Can we make it `private`?

File: buildSrc/src/main/kotlin/io/spine/internal/gradle/ConfigTester.kt [hunk 2]
```diff
@@ -0,0 +1,354 @@
...
+     * of the folder defined by the [source].
+     *
+     * [source] is expected to be another `buildSrc` folder.
+     *
+     * The original `buildSrc` folder, if it exists in this cloned repo, is renamed
+     * to `buildSrc-original`.
+     *
+     * Optionally, takes an [ignoredFolder] which will be excluded from the [source] paths
+     * when copying.
+     *
```
Comment (yuri-sergiichuk) [inline buildSrc/src/main/kotlin/io/spine/internal/gradle/ConfigTester.kt:259]:
```suggestion
```

File: tests/.idea/codeStyles/Project.xml [hunk 3]
```diff
@@ -0,0 +1,10 @@
+<component name="ProjectCodeStyleConfiguration">
+  <code_scheme name="Project" version="173">
+    <JetCodeStyleSettings>
+      <option name="CODE_STYLE_DEFAULTS" value="KOTLIN_OFFICIAL" />
+    </JetCodeStyleSettings>
+    <codeStyleSettings language="kotlin">
+      <option name="CODE_STYLE_DEFAULTS" value="KOTLIN_OFFICIAL" />
+    </codeStyleSettings>
+  </code_scheme>
+</component>
```
Comment (yuri-sergiichuk) [inline tests/.idea/codeStyles/Project.xml:10]: Can you please fix EOF here?

File: tests/.idea/codeStyles/codeStyleConfig.xml [hunk 4]
```diff
@@ -0,0 +1,5 @@
+<component name="ProjectCodeStyleConfiguration">
+  <state>
+    <option name="USE_PER_PROJECT_SETTINGS" value="true" />
+  </state>
+</component>
```
Comment (yuri-sergiichuk) [inline tests/.idea/codeStyles/codeStyleConfig.xml:5]: Can you please fix EOF here?

**Review by yuri-sergiichuk — APPROVED** [review]
@alexander-yevsyukov overall LGTM. Can you please address a couple of minor comments prior to merging the PR?

File: buildSrc/src/main/kotlin/io/spine/internal/gradle/ConfigTester.kt [hunk 5]
```diff
@@ -0,0 +1,354 @@
...
+
+    /**
+     * Adds a test
+     */
+    fun addRepo(repo: URI, branch: Branch): ConfigTester {
+        repos.add(GitRepository(repo, branch))
+        return this
+    }
+
+    fun registerUnder(taskName: String) {
```
[the remark this answers is not in the document]
Comment (alexander-yevsyukov) [reply buildSrc/src/main/kotlin/io/spine/internal/gradle/ConfigTester.kt:88]: This is an update from `config`. It would be better to address it there.

File: buildSrc/src/main/kotlin/io/spine/internal/gradle/ConfigTester.kt [hunk 6]
```diff
@@ -0,0 +1,354 @@
...
+    ) {
+        tasks.register(runGradleName, RunBuild::class.java) {
+            doFirst {
+                println("`${gitRepo.name}`: starting Gradle build...")
+            }
+            doLast {
+                println("*** `${gitRepo.name}`: Gradle build completed. ***")
+            }
+            directory = gitRepo.prepareCheckout(tempFolder).absolutePath
+            maxDurationMins = 30
```
[the remark this answers is not in the document]
Comment (alexander-yevsyukov) [reply buildSrc/src/main/kotlin/io/spine/internal/gradle/ConfigTester.kt:135]: This is an update from `config`. It would be better to address it there.
